# Generated by Django 5.2.1 on 2025-05-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
